### ISSUE TITLE
Mention

### ISSUE THREAD

**Issue by Nufeen** [Nufeen/async-architecture-workshop-2021#1]
@f213, @davydovanton, тегнул вас в [релизе](https://github.com/Nufeen/async-architecture-workshop-2021/releases/tag/v0.1), но не знаю, придёт ли нотификация, на всякий случай дублирую.

Пока 1 коммит, PR не стал создавать, обсуждать можно [в самом коммите](https://github.com/Nufeen/async-architecture-workshop-2021/commit/56da1ff5ad5bcf37c9b0311aaeaa8ca90abd7504).

**Comment by davydovanton** [comment]
привет, а можешь ссылку на репозиторй прислать на почту: support@education.borshev.com или в чат на сайте? еще емейл укажи, что бы тебя найти можно было. Заранее спасибо
